# Generated by Django 5.2.7 on 2025-10-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id_container', models.AutoField(primary_key=True, serialize=False)),
                ('nome_container', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado'), ('cheio', 'Cheio')], default='ativo', max_length=20)),
                ('ultimas_alteracoes', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente_pedido', models.CharField(max_length=20, unique=True)),
                ('nome_cliente_pedido', models.CharField(max_length=100)),
                ('regiao_pedido', models.CharField(max_length=100)),
                ('falta', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3)),
                ('status_pedido', models.CharField(choices=[('separar', 'Separar'), ('separado', 'Separado'), ('entregue', 'Entregue')], default='separar', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimas_alteracoes', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('gramagem_produto', models.CharField(choices=[('800gr', '800 GR'), ('1kg', '1 KG'), ('2kg', '2 KG'), ('2.5kg', '2.5 KG'), ('5kg', '5 KG')], max_length=10)),
                ('status_produto', models.CharField(choices=[('frito_congelado', 'Frito e Congelado'), ('cru_congelado', 'Cru e Congelado')], max_length=20)),
                ('quantidade_produto', models.PositiveIntegerField(default=0)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='APPEstoque.container')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
