# Generated by Django 5.2.7 on 2025-10-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPEstoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
            ],
        ),
    ]
