# Generated by Django 5.2.7 on 2025-10-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPEstoque', '0002_cadastro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email_usuario',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fullname',
            field=models.CharField(default='Ângelo', max_length=150),
            preserve_default=False,
        ),
    ]
