# Generated by Django 5.2.7 on 2025-10-16 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPEstoque', '0003_delete_cadastro_rename_email_usuario_usuario_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id_container', models.AutoField(primary_key=True, serialize=False)),
                ('nome_container', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado'), ('cheio', 'Cheio')], default='ativo', max_length=20)),
                ('ultimas_alteracoes', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente_pedido', models.CharField(max_length=20, unique=True)),
                ('nome_cliente_pedido', models.CharField(max_length=100)),
                ('regiao_pedido', models.CharField(max_length=100)),
                ('falta', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3)),
                ('status_pedido', models.CharField(choices=[('separar', 'Separar'), ('separado', 'Separado'), ('entregue', 'Entregue')], default='separar', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimas_alteracoes', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('gramagem_produto', models.CharField(choices=[('800gr', '800 GR'), ('1kg', '1 KG'), ('2kg', '2 KG'), ('2.5kg', '2.5 KG'), ('5kg', '5 KG')], max_length=10)),
                ('status_produto', models.CharField(choices=[('frito_congelado', 'Frito e Congelado'), ('cru_congelado', 'Cru e Congelado')], max_length=20)),
                ('quantidade_produto', models.PositiveIntegerField(default=0)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='APPEstoque.container')),
            ],
        ),
    ]
